# Generated by Django 5.2.14 on 2026-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('rollo', 'Rollo'), ('bolsa', 'Bolsa')], default='unidad', max_length=20),
        ),
    ]
